### PR TITLE
i227 fix reset passwrod modal and something else

### LINKED ISSUE #227: fix the reset password modal
## Basic Information
**[Give a brief summary of what the issue is about]**
- spacing is all wrong when compared to other modals 

## Other Information
**[Are there any additional information that we should know about?]**

### PR DESCRIPTION
**Pull request by benvarian**
## Change Summary
- made so active avatar actually works on settings page
- made so reset password component looks half decent

**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form

**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information

**[Is there anything in particular in the review that I should be aware of?]**

# Related Issue

- Resolve #227

### CODE REVIEW

File: client/src/views/UserSettingsView.vue [hunk 1]
```diff
@@ -132,7 +132,7 @@ const avatarPaths = ref(
       return {
         url: `avatar${i + 1}.jpg`,
         alt: `avatar${i + 1}`,
-        isSelected: state.avatar === `avatar${i + 1}.jpg`
+        isSelected: parseInt(state.avatar) === i + 1
```
Comment (ChantelleKerr) [inline client/src/views/UserSettingsView.vue:135]: This doesnt work as expected. You are comparing "avatar1.jpg" to a number

**Review by ChantelleKerr — CHANGES_REQUESTED** [review]
Small change - can you also add hover effect when hovering over avatars - might have to do it on both settings and signup pages

**Review by ChantelleKerr — APPROVED** [review]
nice
